
CREATE TABLE if NOT EXISTS Location (
	ID SERIAL PRIMARY KEY,
	Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Beehive (
    ID SERIAL PRIMARY KEY,
    InstallationDate TIMESTAMP NOT NULL,
    LocationID INTEGER NOT NULL,

    FOREIGN KEY (LocationID) REFERENCES Location(ID)
);

CREATE TABLE if NOT EXISTS Sensor (
	ID SERIAL PRIMARY KEY,
	Type TEXT,
	InstallationDate TIMESTAMP NOT NULL,
	LastActivity TIMESTAMP NOT NULL,
	BeehiveID INTEGER NOT NULL,

	FOREIGN KEY (BeehiveID) REFERENCES Beehive(ID)
);

CREATE TABLE if NOT EXISTS MeasurementType (
	ID SERIAL PRIMARY KEY,
	Name TEXT,
	Unit TEXT,
	Description TEXT
);

CREATE TABLE if NOT EXISTS SensorMeasurement (
	ID SERIAL PRIMARY KEY,
	SensorID INTEGER NOT NULL,
	MeasurementTypeID INTEGER NOT NULL,
	
	FOREIGN KEY (SensorID) REFERENCES Sensor(ID),
	FOREIGN KEY (MeasurementTypeID) REFERENCES MeasurementType(ID)
);

CREATE TABLE if NOT EXISTS Data (
	ID SERIAL PRIMARY KEY,
	Value DOUBLE PRECISION NOT NULL,
	Time	TIMESTAMP NOT NULL,
	SensorID INTEGER NOT NULL,
	MeasurementTypeID INTEGER NOT NULL,

	FOREIGN KEY (SensorID) REFERENCES Sensor(ID),
	FOREIGN KEY (MeasurementTypeID) REFERENCES MeasurementType(ID)
);
